// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Sexp = require("./sexp.js");
var Srcloc = require("./srcloc.js");
var Codegen = require("./codegen.js");
var Frontend = require("./frontend.js");
var Comptypes = require("./comptypes.js");

function compile_file(opts, content) {
  var parse_result = Sexp.parse_sexp(Srcloc.combineSrcLocation, Srcloc.start(opts.filename), Srcloc.advance)(content);
  if (parse_result.TAG === /* Success */0) {
    return Comptypes.compMap((function (result) {
                  if (opts.assemble) {
                    return Sexp.encode(result);
                  } else {
                    return Sexp.to_string(result);
                  }
                }), Comptypes.compBind((function (param) {
                      return Codegen.codegen(opts, param);
                    }), Frontend.frontend(opts, parse_result._0)));
  }
  var match = parse_result._0;
  return {
          TAG: /* CompileError */1,
          _0: match[0],
          _1: match[1]
        };
}

exports.compile_file = compile_file;
/* Sexp Not a pure module */
