// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");

var argname_ctr = {
  contents: 0
};

function gensym(name) {
  argname_ctr.contents = argname_ctr.contents + 1 | 0;
  return Curry._2(Printf.sprintf(/* Format */{
                  _0: {
                    TAG: /* String */2,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: /* String_literal */11,
                      _0: "_$_",
                      _1: {
                        TAG: /* Int */4,
                        _0: /* Int_d */0,
                        _1: /* No_padding */0,
                        _2: /* No_precision */0,
                        _3: /* End_of_format */0
                      }
                    }
                  },
                  _1: "%s_$_%d"
                }), name, argname_ctr.contents);
}

exports.argname_ctr = argname_ctr;
exports.gensym = gensym;
/* No side effect */
