// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var JsSha256 = require("js-sha256");

function create(param) {
  return JsSha256.sha256.create();
}

exports.create = create;
/* js-sha256 Not a pure module */
