// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function map(f, a) {
  if (a !== undefined) {
    return Caml_option.some(Curry._1(f, Caml_option.valFromOption(a)));
  }
  
}

function bind(f, a) {
  if (a !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(a));
  }
  
}

exports.map = map;
exports.bind = bind;
/* No side effect */
