// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Srcloc = require("./srcloc.js");

var primloc = Srcloc.start("*prims*");

var prims_0 = [
  "q",
  {
    TAG: /* Integer */2,
    _0: [
      primloc,
      "1"
    ]
  }
];

var prims_1 = {
  hd: [
    "a",
    {
      TAG: /* Integer */2,
      _0: [
        primloc,
        "2"
      ]
    }
  ],
  tl: {
    hd: [
      "i",
      {
        TAG: /* Integer */2,
        _0: [
          primloc,
          "3"
        ]
      }
    ],
    tl: {
      hd: [
        "c",
        {
          TAG: /* Integer */2,
          _0: [
            primloc,
            "4"
          ]
        }
      ],
      tl: {
        hd: [
          "f",
          {
            TAG: /* Integer */2,
            _0: [
              primloc,
              "5"
            ]
          }
        ],
        tl: {
          hd: [
            "r",
            {
              TAG: /* Integer */2,
              _0: [
                primloc,
                "6"
              ]
            }
          ],
          tl: {
            hd: [
              "l",
              {
                TAG: /* Integer */2,
                _0: [
                  primloc,
                  "7"
                ]
              }
            ],
            tl: {
              hd: [
                "x",
                {
                  TAG: /* Integer */2,
                  _0: [
                    primloc,
                    "8"
                  ]
                }
              ],
              tl: {
                hd: [
                  "=",
                  {
                    TAG: /* Integer */2,
                    _0: [
                      primloc,
                      "9"
                    ]
                  }
                ],
                tl: {
                  hd: [
                    ">s",
                    {
                      TAG: /* Integer */2,
                      _0: [
                        primloc,
                        "10"
                      ]
                    }
                  ],
                  tl: {
                    hd: [
                      "sha256",
                      {
                        TAG: /* Integer */2,
                        _0: [
                          primloc,
                          "11"
                        ]
                      }
                    ],
                    tl: {
                      hd: [
                        "substr",
                        {
                          TAG: /* Integer */2,
                          _0: [
                            primloc,
                            "12"
                          ]
                        }
                      ],
                      tl: {
                        hd: [
                          "strlen",
                          {
                            TAG: /* Integer */2,
                            _0: [
                              primloc,
                              "13"
                            ]
                          }
                        ],
                        tl: {
                          hd: [
                            "concat",
                            {
                              TAG: /* Integer */2,
                              _0: [
                                primloc,
                                "14"
                              ]
                            }
                          ],
                          tl: {
                            hd: [
                              "+",
                              {
                                TAG: /* Integer */2,
                                _0: [
                                  primloc,
                                  "16"
                                ]
                              }
                            ],
                            tl: {
                              hd: [
                                "-",
                                {
                                  TAG: /* Integer */2,
                                  _0: [
                                    primloc,
                                    "17"
                                  ]
                                }
                              ],
                              tl: {
                                hd: [
                                  "*",
                                  {
                                    TAG: /* Integer */2,
                                    _0: [
                                      primloc,
                                      "18"
                                    ]
                                  }
                                ],
                                tl: {
                                  hd: [
                                    "/",
                                    {
                                      TAG: /* Integer */2,
                                      _0: [
                                        primloc,
                                        "19"
                                      ]
                                    }
                                  ],
                                  tl: {
                                    hd: [
                                      "divmod",
                                      {
                                        TAG: /* Integer */2,
                                        _0: [
                                          primloc,
                                          "20"
                                        ]
                                      }
                                    ],
                                    tl: {
                                      hd: [
                                        ">",
                                        {
                                          TAG: /* Integer */2,
                                          _0: [
                                            primloc,
                                            "21"
                                          ]
                                        }
                                      ],
                                      tl: {
                                        hd: [
                                          "ash",
                                          {
                                            TAG: /* Integer */2,
                                            _0: [
                                              primloc,
                                              "22"
                                            ]
                                          }
                                        ],
                                        tl: {
                                          hd: [
                                            "lsh",
                                            {
                                              TAG: /* Integer */2,
                                              _0: [
                                                primloc,
                                                "23"
                                              ]
                                            }
                                          ],
                                          tl: {
                                            hd: [
                                              "logand",
                                              {
                                                TAG: /* Integer */2,
                                                _0: [
                                                  primloc,
                                                  "24"
                                                ]
                                              }
                                            ],
                                            tl: {
                                              hd: [
                                                "logior",
                                                {
                                                  TAG: /* Integer */2,
                                                  _0: [
                                                    primloc,
                                                    "25"
                                                  ]
                                                }
                                              ],
                                              tl: {
                                                hd: [
                                                  "logxor",
                                                  {
                                                    TAG: /* Integer */2,
                                                    _0: [
                                                      primloc,
                                                      "26"
                                                    ]
                                                  }
                                                ],
                                                tl: {
                                                  hd: [
                                                    "lognot",
                                                    {
                                                      TAG: /* Integer */2,
                                                      _0: [
                                                        primloc,
                                                        "27"
                                                      ]
                                                    }
                                                  ],
                                                  tl: {
                                                    hd: [
                                                      "point_add",
                                                      {
                                                        TAG: /* Integer */2,
                                                        _0: [
                                                          primloc,
                                                          "29"
                                                        ]
                                                      }
                                                    ],
                                                    tl: {
                                                      hd: [
                                                        "pubkey_for_exp",
                                                        {
                                                          TAG: /* Integer */2,
                                                          _0: [
                                                            primloc,
                                                            "30"
                                                          ]
                                                        }
                                                      ],
                                                      tl: {
                                                        hd: [
                                                          "not",
                                                          {
                                                            TAG: /* Integer */2,
                                                            _0: [
                                                              primloc,
                                                              "32"
                                                            ]
                                                          }
                                                        ],
                                                        tl: {
                                                          hd: [
                                                            "any",
                                                            {
                                                              TAG: /* Integer */2,
                                                              _0: [
                                                                primloc,
                                                                "33"
                                                              ]
                                                            }
                                                          ],
                                                          tl: {
                                                            hd: [
                                                              "all",
                                                              {
                                                                TAG: /* Integer */2,
                                                                _0: [
                                                                  primloc,
                                                                  "34"
                                                                ]
                                                              }
                                                            ],
                                                            tl: {
                                                              hd: [
                                                                "softfork",
                                                                {
                                                                  TAG: /* Integer */2,
                                                                  _0: [
                                                                    primloc,
                                                                    "36"
                                                                  ]
                                                                }
                                                              ],
                                                              tl: /* [] */0
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

var prims = {
  hd: prims_0,
  tl: prims_1
};

function primquote(l, a) {
  return {
          TAG: /* Cons */1,
          _0: [
            l,
            {
              TAG: /* Integer */2,
              _0: [
                l,
                "1"
              ]
            },
            a
          ]
        };
}

function primcons(l, a, b) {
  return {
          TAG: /* Cons */1,
          _0: [
            l,
            {
              TAG: /* Integer */2,
              _0: [
                l,
                "4"
              ]
            },
            {
              TAG: /* Cons */1,
              _0: [
                l,
                a,
                {
                  TAG: /* Cons */1,
                  _0: [
                    l,
                    b,
                    {
                      TAG: /* Nil */0,
                      _0: l
                    }
                  ]
                }
              ]
            }
          ]
        };
}

function primapply(l, a, b) {
  return {
          TAG: /* Cons */1,
          _0: [
            l,
            {
              TAG: /* Integer */2,
              _0: [
                l,
                "2"
              ]
            },
            {
              TAG: /* Cons */1,
              _0: [
                l,
                a,
                {
                  TAG: /* Cons */1,
                  _0: [
                    l,
                    b,
                    {
                      TAG: /* Nil */0,
                      _0: l
                    }
                  ]
                }
              ]
            }
          ]
        };
}

function primexc(l, a, b) {
  return {
          TAG: /* Cons */1,
          _0: [
            l,
            {
              TAG: /* Integer */2,
              _0: [
                l,
                "8"
              ]
            },
            {
              TAG: /* Cons */1,
              _0: [
                l,
                a,
                {
                  TAG: /* Cons */1,
                  _0: [
                    l,
                    b,
                    {
                      TAG: /* Nil */0,
                      _0: l
                    }
                  ]
                }
              ]
            }
          ]
        };
}

function primop(l, op, args) {
  return {
          TAG: /* Cons */1,
          _0: [
            l,
            op,
            args
          ]
        };
}

exports.primloc = primloc;
exports.prims = prims;
exports.primquote = primquote;
exports.primcons = primcons;
exports.primapply = primapply;
exports.primexc = primexc;
exports.primop = primop;
/* primloc Not a pure module */
