// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Sexp = require("./sexp.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Srcloc = require("./srcloc.js");

function run_to_string(cvt, r) {
  switch (r.TAG | 0) {
    case /* RunError */0 :
        var match = r._0;
        return Curry._2(Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: {
                            TAG: /* String_literal */11,
                            _0: ": ",
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: {
                                TAG: /* Char_literal */12,
                                _0: /* '\n' */10,
                                _1: /* End_of_format */0
                              }
                            }
                          }
                        },
                        _1: "%s: %s\n"
                      }), Srcloc.toString(match[0]), match[1]);
    case /* RunExn */1 :
        var match$1 = r._0;
        return Curry._2(Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: {
                            TAG: /* String_literal */11,
                            _0: ": throw(x) ",
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: {
                                TAG: /* Char_literal */12,
                                _0: /* '\n' */10,
                                _1: /* End_of_format */0
                              }
                            }
                          }
                        },
                        _1: "%s: throw(x) %s\n"
                      }), Srcloc.toString(match$1[0]), Sexp.to_string(match$1[1]));
    case /* RunOk */2 :
        return Curry._1(Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: /* End_of_format */0
                        },
                        _1: "%s"
                      }), Curry._1(cvt, r._0));
    
  }
}

exports.run_to_string = run_to_string;
/* Sexp Not a pure module */
