open Sexp

let prims : (string * Srcloc.t sexp) list =
  [ ("q", Integer (Srcloc.start, "1"))
  ; ("a", Integer (Srcloc.start, "2"))
  ; ("i", Integer (Srcloc.start, "3"))
  ; ("c", Integer (Srcloc.start, "4"))
  ; ("f", Integer (Srcloc.start, "5"))
  ; ("r", Integer (Srcloc.start, "6"))
  ; ("l", Integer (Srcloc.start, "7"))
  ; ("x", Integer (Srcloc.start, "8"))
  ; ("=", Integer (Srcloc.start, "9"))
  ; (">s", Integer (Srcloc.start, "10"))
  ; ("sha256", Integer (Srcloc.start, "11"))
  ; ("substr", Integer (Srcloc.start, "12"))
  ; ("strlen", Integer (Srcloc.start, "13"))
  ; ("concat", Integer (Srcloc.start, "14"))
  ; ("+", Integer (Srcloc.start, "16"))
  ; ("-", Integer (Srcloc.start, "17"))
  ; ("*", Integer (Srcloc.start, "18"))
  ; ("/", Integer (Srcloc.start, "19"))
  ; ("divmod", Integer (Srcloc.start, "20"))
  ; (">", Integer (Srcloc.start, "21"))
  ; ("ash", Integer (Srcloc.start, "22"))
  ; ("lsh", Integer (Srcloc.start, "23"))
  ; ("logand", Integer (Srcloc.start, "24"))
  ; ("logior", Integer (Srcloc.start, "25"))
  ; ("logxor", Integer (Srcloc.start, "26"))
  ; ("lognot", Integer (Srcloc.start, "27"))
  ; ("point_add", Integer (Srcloc.start, "29"))
  ; ("pubkey_for_exp", Integer (Srcloc.start, "30"))
  ; ("not", Integer (Srcloc.start, "32"))
  ; ("any", Integer (Srcloc.start, "33"))
  ; ("all", Integer (Srcloc.start, "34"))
  ; ("softfork", Integer (Srcloc.start, "36"))
  ]
